backend:
  name: git-gateway
  branch: main
  repo: kr8n3r/elmbridge-road-runners
media_folder: "public/images"
public_folder: "images"
publish_mode: editorial_workflow
collections:
  - name: "content"
    label: "Pages"
    label_singular: "Page"
    folder: "pages/content"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    summary: '{{filename}} -- {{title}}'
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}