backend:
  name: git-gateway
  branch: main
  repo: kr8n3r/elmbridge-road-runners
media_folder: "public/images"
public_folder: "images"
publish_mode: editorial_workflow
collections:
  - name: "pages" # Used in routes, e.g., /admin/collections/blog
    label: "Pages" # Used in the UI
    folder: "pages/content" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}